Albaque/Albaque/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Albaque.Models;

namespace Albaque.Controllers
{
    public class ClientController : Controller
    {
        private ChiffrageDBContext db = new ChiffrageDBContext();

        // GET: /Client/
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: /Client/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: /Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Client/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,nom,adresse_Mail,numero_Tel")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: /Client/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: /Client/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,nom,adresse_Mail,numero_Tel")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: /Client/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: /Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Albaque/Albaque/Controllers/ProjetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Albaque.Models;
using Albaque.ViewModels;

namespace Albaque.Controllers
{
    public class ProjetController : Controller
    {
        private ChiffrageDBContext db = new ChiffrageDBContext();

        // GET: /Projet/
        public ActionResult Index()
        {
            return View(db.Projets.Include(c => c.client).ToList());
        }

        // GET: /Projet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projet projet = db.Projets.Find(id);
            if (projet == null)
            {
                return HttpNotFound();
            }
            return View(projet);
        }

        // GET: /Projet/Create
        public ActionResult Create()
        {
            var clients = db.Clients.ToList();

            var viewModel = new ProjetClientViewModel
            {
                projet = new Projet(),
                clients = clients,
                newClient = new Client()
            };
           
            return View(viewModel);
           
        }

        // POST: /Projet/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="Id,Nom,Duree,Delai,Date_Debut,Date_Fin")] Projet projet)
        public ActionResult Create(Projet projet)
        {
            
            if (ModelState.IsValid)
            {
                db.Projets.Add(projet);
                
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            var errors = ModelState
                .Where(x => x.Value.Errors.Count > 0)
                .Select(x => new { x.Key, x.Value.Errors })
                .ToArray();
            return View(projet);
        }




        // GET: /Projet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projet projet = db.Projets.Find(id);
            if (projet == null)
            {
                return HttpNotFound();
            }
            else
            {
                var clients = db.Clients.ToList();

                var viewModel = new ProjetClientViewModel
                {
                    projet = projet,
                    clients = clients
                };
                return View(viewModel);
            }

        }

        // POST: /Projet/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include="Id,Nom,Duree,Delai,Date_Debut,Date_Fin")] Projet projet)
        public ActionResult Edit(ProjetClientViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viewModel.projet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewModel.projet);
        }

        // GET: /Projet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projet projet = db.Projets.Find(id);
            if (projet == null)
            {
                return HttpNotFound();
            }
            return View(projet);
        }

        // POST: /Projet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projet projet = db.Projets.Find(id);
            db.Projets.Remove(projet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Albaque/Albaque/Controllers/TacheController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Albaque.Models;
using Albaque.ViewModels;

namespace Albaque.Controllers
{
    public class TacheController : Controller
    {
        private ChiffrageDBContext db = new ChiffrageDBContext();

        // GET: /Tache/
        public ActionResult Index()
        {
            return View(db.Taches.Include(com => com.complexite).Include(cat => cat.categorie).Include(tec => tec.technologie).ToList());
        }

        // GET: /Tache/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tache tache = db.Taches.Find(id);
            if (tache == null)
            {
                return HttpNotFound();
            }
            return View(tache);
        }

        // GET: /Tache/Create
        public ActionResult Create()
        {
            var categories = db.Categories.ToList();
            var complexites = db.Complexites.ToList();
            var technologies = db.Technologies.ToList();

            var viewModel = new TacheInformationViewModel
            {
                tache = new Tache(),
                categories = categories,
                complexites = complexites,
                technologies = technologies
            };
            return View(viewModel);
        }

        // POST: /Tache/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="Id,nom,description,charge")] Tache tache)
        public ActionResult Create(TacheInformationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                db.Taches.Add(viewModel.tache);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var errors = ModelState
               .Where(x => x.Value.Errors.Count > 0)
               .Select(x => new { x.Key, x.Value.Errors })
               .ToArray();

            return View(viewModel.tache);
        }

        // GET: /Tache/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tache tache = db.Taches.Find(id);           

            if (tache == null)
            {
                return HttpNotFound();
            }
            else
            {

                var categories = db.Categories.ToList();
                var complexites = db.Complexites.ToList();
                var technologies = db.Technologies.ToList();
                var viewModel = new TacheInformationViewModel
                {
                    tache = tache,
                    categories = categories,
                    complexites = complexites,
                    technologies = technologies
                };
                return View(viewModel);
            }
           // return View("Index");
        }

        // POST: /Tache/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include="Id,nom,description,charge")] Tache tache)
        public ActionResult Edit(TacheInformationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viewModel.tache).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewModel.tache);
        }

        // GET: /Tache/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tache tache = db.Taches.Find(id);
            if (tache == null)
            {
                return HttpNotFound();
            }
            db.Taches.Remove(tache);
            db.SaveChanges();
            return View(tache);
        }

        // POST: /Tache/Delete/5
        [HttpDelete, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tache tache = db.Taches.Find(id);
            db.Taches.Remove(tache);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Albaque/Albaque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/toastr.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/datatables/css/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/scripts/jquery-1.10.2.js"></script>
    <script src="~/scripts/modernizr-2.6.2.js"></script>
    <script src="~/scripts/bootbox.js"></script>
    <script src="~/scripts/toastr.js"></script>
    @*<script src="~/scripts/datatables/jquery.datatables.js"></script>
    <script src="~/scripts/datatables/datatables.bootstrap.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></script>*@
    <style>
        .container {
            margin-top: 10px;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
            margin-top: 0;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Albaque", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Chiffrage</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Création", "Create", "Chiffrage")</li>
                            <li>@Html.ActionLink("Visualisation", "Index", "Client")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projet</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Création", "Create", "Projet")</li>
                            <li>@Html.ActionLink("Visualisation", "Index", "Projet")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Client</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Création", "Create", "Client")</li>
                            <li>@Html.ActionLink("Visualisation", "Index", "Client")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tache</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Création", "Create", "Tache")</li>
                            <li>@Html.ActionLink("Visualisation", "Index", "Tache")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Se déconnecter", "LogOff", "Login", null, new { @class = "navbar-brand" })</li>
                </ul>
                @*<ul class="nav navbar-nav">
                </ul>*@
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Albaque</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>